# Generated by Django 5.1.7 on 2025-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("student_id", models.CharField(max_length=50, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("score", models.FloatField()),
                ("grade", models.CharField(max_length=10)),
                ("exam_year", models.IntegerField()),
            ],
        ),
    ]
