# Generated by Django 5.1.7 on 2025-03-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentresult",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="student_id",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="student_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="subject",
            field=models.CharField(max_length=100),
        ),
    ]
