# Generated by Django 5.1.7 on 2025-03-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_studentresult_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentResultFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="studentresult",
            unique_together={("student_id", "subject", "exam_year")},
        ),
        migrations.AlterField(
            model_name="studentresult",
            name="student_id",
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name="studentresult",
            name="score",
        ),
    ]
