services:
  - type: web
    name: imam-islamic
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn imam_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: imam_islamic.settings
      - key: PYTHON_VERSION
        value: 3.10
