# Generated by Django 5.1.7 on 2025-04-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0002_delete_blogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("image", models.ImageField(upload_to="home_images/")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
