# Generated by Django 5.1.7 on 2025-04-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_homeimage_active_remove_homeimage_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="homepage_images/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="HomeImage",
        ),
    ]
