# Generated by Django 5.1.7 on 2025-04-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_homepageimage_delete_homeimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="sliders/")),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="حدد ترتيب الصورة في السليدر"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="تفعيل أو تعطيل السليدر"
                    ),
                ),
            ],
        ),
    ]
