# Generated by Django 5.1.7 on 2025-04-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_advertisement"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Advertisement",
        ),
    ]
